/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2024-10-20 13:05:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>POWPOW</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/index.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"assets/css/login/login.css\"/>\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"assets/images/favicon.ico\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"login-main\">\r\n");
      out.write("      <div class=\"logo-box\">\r\n");
      out.write("        <a href=\"http://127.0.0.1:5500/powpow-login/main.html\">\r\n");
      out.write("          <img id=\"logo\" src=\"assets/images/logo.png\" alt=\"로고\" />\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div>\r\n");
      out.write("        <div class=\"tap\">\r\n");
      out.write("          <button class=\"member-btn\">회원</button>\r\n");
      out.write("          <button class=\"seller-btn\">판매자</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"main\">\r\n");
      out.write("          <div class=\"main-content mebmer\">\r\n");
      out.write("            <div id=\"idFind\" class=\"input\">\r\n");
      out.write("              <input class=\"inputbutton1\" type=\"email\" name=\"id\" placeholder=\"회원 아이디(이메일)를 입력해주세요\">\r\n");
      out.write("              <p id=\"id-result\"></p>\r\n");
      out.write("              <input class=\"inputbutton\" type=\"password\" name=\"password\" placeholder=\"회원 비밀번호를 입력해주세요\">\r\n");
      out.write("              <p id=\"password-result\"></p>\r\n");
      out.write("\r\n");
      out.write("            <button class=\"login-button\">로그인</button>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"box4\">\r\n");
      out.write("            <div class=\"box3\">\r\n");
      out.write("              <div class=\"savebox\">\r\n");
      out.write("                <label for=\"saveEmail\">\r\n");
      out.write("                  <input type=\"checkbox\" name=\"saveEmail\" id=\"saveEmail\" />\r\n");
      out.write("                  <span class=\"checkmark\"></span>\r\n");
      out.write("                </label>\r\n");
      out.write("                <p class=\"id-save\">아이디 저장</p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <a class=\"forgot\" href=\"http://localhost:9000/powpow/find.jsp\">아이디 혹은 비밀번호를 잊어버리셨나요?</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"text-box\">\r\n");
      out.write("            <p class=\"text\">계정이 없으신가요?</p>\r\n");
      out.write("            <p class=\"text1\">|</p>\r\n");
      out.write("            <a class=\"text\" href=\"http://localhost:9000/powpow/join.jsp\">회원가입</a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <p class=\"text2\">Or continue with</p>\r\n");
      out.write("          <div class=\"simple-login-box\">\r\n");
      out.write("            <img class=\"simple-login\" src=\"assets/images/kakao.svg\" alt=\"카카오\">\r\n");
      out.write("            <img class=\"simple-login\" src=\"assets/images/naver.svg\" alt=\"네이버\">\r\n");
      out.write("            <img class=\"simple-login\" src=\"assets/images/google.svg\" alt=\"구글\">\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("          <div class=\"main-content seller\" style=\"display: none;\">\r\n");
      out.write("            <div id=\"idFind\" class=\"input\">\r\n");
      out.write("              <input class=\"inputbutton1\" type=\"id\" name=\"id\" placeholder=\"판매자 아이디(이메일)를 입력해주세요\">\r\n");
      out.write("              <input class=\"inputbutton\" type=\"password\" name=\"password\" placeholder=\"판매자 비밀번호를 입력해주세요\">\r\n");
      out.write("    \r\n");
      out.write("            <button type=\"button\" class=\"login-button\">로그인</button>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"box4\">\r\n");
      out.write("            <div class=\"box3\">\r\n");
      out.write("              <div class=\"savebox\">\r\n");
      out.write("                <label for=\"saveEmail2\">\r\n");
      out.write("                  <input type=\"checkbox\" name=\"saveEmail\" id=\"saveEmail2\" />\r\n");
      out.write("                  <span class=\"checkmark2\"></span>\r\n");
      out.write("                </label>\r\n");
      out.write("                <p class=\"id-save\">아이디 저장</p>\r\n");
      out.write("              </div>\r\n");
      out.write("              <a class=\"forgot\" href=\"http://127.0.0.1:5500/powpow-login/find.html\">아이디 혹은 비밀번호를 잊어버리셨나요?</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"text-box\">\r\n");
      out.write("            <p class=\"text\">계정이 없으신가요?</p>\r\n");
      out.write("            <p class=\"text1\">|</p>\r\n");
      out.write("            <a class=\"text\" href=\"http://127.0.0.1:5500/powpow-login/join.html\">회원가입</a>\r\n");
      out.write("          </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"bottom-box\">\r\n");
      out.write("            <p class=\"bottom-text\">이용약관</p>\r\n");
      out.write("            <p class=\"bottom-text1\">|</p>\r\n");
      out.write("            <p class=\"bottom-text\">개인정보처리방침</p>\r\n");
      out.write("            <p class=\"bottom-text1\">|</p>\r\n");
      out.write("            <p class=\"bottom-text\">책임의 한계와 법적고지</p>\r\n");
      out.write("            <p class=\"bottom-text1\">|</p>\r\n");
      out.write("            <p class=\"bottom-text\">회원정보 고객센터</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	  const mebmerBtn = document.querySelector(\".member-btn\");\r\n");
      out.write("	  const sellerBtn = document.querySelector(\".seller-btn\");\r\n");
      out.write("	  const main = document.querySelectorAll(\".main-content\");\r\n");
      out.write("	\r\n");
      out.write("	  mebmerBtn.addEventListener(\"click\", () => {\r\n");
      out.write("	    main[0].style.display = \"block\";\r\n");
      out.write("	    main[1].style.display = \"none\";\r\n");
      out.write("	  })\r\n");
      out.write("	\r\n");
      out.write("	  sellerBtn.addEventListener(\"click\", () => {\r\n");
      out.write("	    main[0].style.display = \"none\";\r\n");
      out.write("	    main[1].style.display = \"block\";\r\n");
      out.write("	  })\r\n");
      out.write("  </script>\r\n");
      out.write("  \r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
