/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2024-10-22 05:18:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class buyer_002daccount_002dfind_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>POWPOW</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../assets/css/index.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../assets/css/login/buyer-account-find.css\"/>\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"../assets/images/favicon.ico\"/>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <div  class=\"find-main\">\r\n");
      out.write("    <div class=\"logo-box\">\r\n");
      out.write("      <a href=\"http://127.0.0.1:5500/powpow-login/main.html\">\r\n");
      out.write("        <img id=\"logo\" src=\"../assets/images/login/logo.png\" alt=\"로고\" />\r\n");
      out.write("      </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div>\r\n");
      out.write("      <div class=\"tap\">\r\n");
      out.write("        <button class=\"id-btn\">아이디 찾기</button>\r\n");
      out.write("        <button class=\"password-btn\">비밀번호 찾기</button>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"main-content id\" class=\"id\">\r\n");
      out.write("          <div class=\"input\">\r\n");
      out.write("            <div>\r\n");
      out.write("              <p>이름</p>\r\n");
      out.write("              <input class=\"inputbutton\" type=\"text\" name=\"id\" placeholder=\"이름\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("              <p>휴대폰 번호</p>\r\n");
      out.write("              <div class=\"input-container\">\r\n");
      out.write("                <input class=\"inputbutton\" type=\"number\" name=\"phone\" placeholder=\"휴대폰 번호 입력 ('-'제외 11자리 입력)\">\r\n");
      out.write("                <button class=\"auth-button\">인증</button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <a href=\"http://localhost:9000/powpow/buyer-id-find-complete.jsp\">\r\n");
      out.write("            <button class=\"next-button\">다음</button>\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"main-content password\" style=\"display: none;\" class=\"password\">\r\n");
      out.write("        <div class=\"input\">\r\n");
      out.write("          <div>\r\n");
      out.write("            <p>아이디</p>\r\n");
      out.write("            <input class=\"inputbutton\" type=\"text\" name=\"id\" placeholder=\"아이디(이메일)\">\r\n");
      out.write("          </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <p class=\"text2\">비밀번호 찾기 방법을 선택해주세요.</p>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"raido-box\">\r\n");
      out.write("            <label for=\"user_a\">\r\n");
      out.write("              <input type=\"radio\" name=\"user\" id=\"user_a\" value=\"A\">\r\n");
      out.write("                <p class=\"text1\">등록된 이메일</p>\r\n");
      out.write("  \r\n");
      out.write("            </label>\r\n");
      out.write("            <label for=\"user_b\">\r\n");
      out.write("              <input type=\"radio\" name=\"user\" id=\"user_b\" value=\"B\">\r\n");
      out.write("                <p class=\"text1\">등록된 휴대폰</p>\r\n");
      out.write("            </label>\r\n");
      out.write("          </div>\r\n");
      out.write("            <button class=\"next-button1\">다음</button>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <script src=\"../assets/js/login/buyer-account-find.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
